# Generated by Django 3.2.9 on 2021-12-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile_no', models.IntegerField(max_length=10)),
                ('minimum_quantity', models.IntegerField()),
                ('maximum_quantity', models.IntegerField()),
                ('pincode', models.IntegerField(max_length=6)),
            ],
        ),
    ]
